Updated dependency
fluttertools/pub_api_client pull request #28
Opened 2022-10-28 12:36 UTC by ashutosh2014

2022-11-01 16:23 UTC, leoafarias approved these changes
LGTM

2022-11-03 23:36 UTC, leoafarias requested changes

2022-11-03 23:36 UTC, leoafarias commented on lib/src/helpers/recursive_paging.dart
> +  final List<PackageResult> lstPackages = [];
Can you just change the code to continue to assign to the variable `packages`? Is packages a readonly value? 
If so can you try doing something like 

```
final packages = [...prevResults.packages];
```

and see if this solves it.

2022-11-04 04:13 UTC, ashutosh2014 commented on lib/src/helpers/recursive_paging.dart
> +  final List<PackageResult> lstPackages = [];
Thanks for the suggestion. Yes, that one resolves the problem of an unmodifiable list.

2022-12-19 14:38 UTC, merged